project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :contacts
  end
  resources :contacts
  get '/search' => 'contacts#search', :as => 'search_page'

  root to: 'welcome#index'
end

project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

project/app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :phone, :email, presence: true
  validates :phone, format: { with: /\d{3}-\d{3}-\d{4}/, message: "xxx-xxx-xxxx format required" }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }


  def self.search(params = {})
    return find_name(params[:search]) if params[:search].present?

    all
  end

  scope :find_name, ->(search) { where("name LIKE :search", search: "%#{search}%") }

  belongs_to :user

end

project/app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable
  validates :name, presence: true

  has_many :contacts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

      def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
      end
end

project/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [ :destroy, :update, :edit ]

  def search
    if params[:search].blank?
      redirect_to(root_path, alert: "Empty field!")
    else
      @contacts = Contact.search(params)
   end
  end

  def index
    @contacts = Contact.order('name ASC')
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = current_user.contacts.build(contact_params)
    if @contact.save
      flash[:success] = "Contact: #{@contact.name} was successfully created!"
      redirect_to contacts_path
    else
      render :new
    end
  end

  def destroy
    if @contact.destroy
      flash[:notice] = "Contact: #{@contact.name} was successfully deleted"
      redirect_to contacts_path
    end
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      flash[:notice] = "Contact: #{@contact.name} was successfully updated"
      redirect_to contacts_path
    else
      render :edit
    end
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :phone, :email)
  end
end

project/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to contacts_path
    end
  end

end

project/app/helpers/application_helper.rb
module ApplicationHelper
end

project/app/helpers/contact_helper.rb
module ContactHelper
end

project/app/helpers/home_helper.rb
module HomeHelper
end

project/app/views/contacts/_contact.html.erb
<div>
  <tr>
    <td><%= contact.name %></td>
    <td><%= contact.phone %></td>
    <td><%= contact.email %></td>
    <td><%= button_to "Edit", edit_contact_path(contact), :method => :get, class: "edit-button" %></td>
    <td><%= link_to contact_path(contact), method: :delete, data: { confirm: "Are you sure you would like to delete Contact: #{contact.name}" }, :class => "no-link", :id => "delete-contact-#{contact.id}"  do %>
      <%= image_tag "icon-delete.svg" %>
    <% end %></td>
  </tr>
</div>

project/app/views/contacts/_form.html.erb
<%= form_for @contact do |f| %>
  <% if @contact.errors.any? %>
    <div class="errors-div">
      <div class="errors">
        <h2>1 error prohibited this user from being saved:</h2>
        <ul>
          <% @contact.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="login-container">
    <div class="form-container">
      <% if @contact.user_id == current_user.id %>
        <h1 class="new-contact-title">Edit Contact</h1>
        <hr class="login-hr"></hr>
      <% else %>
        <h1 class="new-contact-title">New Contact</h1>
        <hr class="login-hr"></hr>
      <% end %>

      <div class="field">
        <%= f.label :name, 'Name' %><br/>
        <%= f.text_field :name, class: "input-small" %>
        <br/>
      </div>

      <div class="field">
        <%= f.label :phone, 'Phone' %><br/>
        <%= f.text_field :phone, class: "input-small" %>
        <br/>
      </div>

      <div class="field">
        <%= f.label :email, 'Email' %><br/>
        <%= f.text_field :email,  class: "input-small" %>
        <br/>
      </div>

      <div class="actions">
        <%= f.submit 'Submit', class: 'btn-primary' %>
        <div class="additional-links">
          <%= link_to 'Back', contacts_path, class: "back-link"%>
        </div>
      </div>
    </div>
  </div>
<% end %>

project/app/views/contacts/edit.html.erb
<div>
  <% if current_user.id == @contact.user_id %>
    <%= render "form" %>
  <% else %>
    <h1 style="text-align: center">Not found!</h1>
  <% end %>
</div>

project/app/views/contacts/index.html.erb
<div>
  <h1 class="contacts-title"> Contacts</h1>
  <div class="contact-div">
    <table style="width: 80%">
      <tr class="table-head">
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th></th>
        <th></th>
      </tr>
      <% @contacts.each do |contact| %>
        <% if current_user.id == contact.user_id %>
          <%= render partial: "contact", locals: { contact: contact } %>
        <% end %>
      <% end %>
    </table>
  </div>
</div>

project/app/views/contacts/new.html.erb
<div>
    <%= render "form" %>
</div>

project/app/views/contacts/search.html.erb
<div>
  <h1 class="contacts-title">Search Results</h1>
  <div class="contact-div">
    <table style="width: 80%">
      <tr class="table-head">
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th></th>
        <th></th>
      </tr>
      <% @contacts.each do |contact| %>
        <% if current_user.id == contact.user_id %>
          <%= render partial: "contact", locals: { contact: contact } %>
        <% end %>
      <% end %>
    </table>
  </div>
</div>

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactListApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch&display=swap" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="navbar">
    <% if user_signed_in? %>
      <%= form_tag(search_page_path, method: :get, class: "input-group") do %>
        <%= link_to "#{current_user.name}'s Contacts", contacts_path, class: "navbar-link" %>
        <%= link_to "Add contact", new_contact_path, class: "navbar-link" %>
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <%= search_field_tag :search, params[:search], placeholder: " Search contacts", class: "search-input" %>
        <%= button_tag "Search", :name => nil, class: "search-button" %>
      <% end %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </div>
    <hr class="navbar-hr"/>

  <body>

  <%= yield %>

  </body>
</html>

project/app/views/welcome/index.html.erb
<div class='welcome-page'>
  <h1 class='welcome-title'>Welcome to FriendBook!</h1>
  <div>
    <h2>Sign up today. It's free!</h2>
    <%= button_to "Sign up",  new_user_registration_path, method: :get , class: "btn-third" %>
    <h2>Already have an account? Sign in!</h2>
    <%= button_to "Login",  new_user_session_path, class: "btn-third" %>
  </div>
</div>